[package]
name = "projectatlas-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
blake3.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
toon-format.workspace = true

[dev-dependencies]
object.workspace = true
sha2.workspace = true
tar.workspace = true
tempfile.workspace = true
zstd.workspace = true

[lints]
workspace = true
