// @generated by `cargo projectatlas-lints language-registry write`; do not edit.
//! Generated CLI language policy language-registry projection.

pub(crate) const LANGUAGE_REGISTRY_SOURCE_LOCK_SHA256: &str =
    "6dfd95d138cd3f575f160c759bc5f63000a897a320c8a3b4d7505e1b803bed4e";
pub(crate) const LANGUAGE_REGISTRY_CONTRACT_SHA256: &str =
    "61153a34d7dd0d53686679726795c5e19ba86a19a5421d98d38b5e0f8b69d564";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum ParserSupport {
    Native,
    Manifest,
    Structural,
    Fallback,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum SummaryAdapter {
    None,
    Markdown,
    Json,
    Yaml,
    Css,
    Html,
    Toon,
    ConfigText,
    Toml,
    Xml,
    PowerShell,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum SymbolRouteKind {
    Skip,
    BuiltIn,
    Manifest,
    Structural,
    Fallback,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct LanguagePolicy {
    pub(crate) public_mode: &'static str,
    pub(crate) parser_support: ParserSupport,
    pub(crate) summary_adapter: SummaryAdapter,
    pub(crate) symbol_route: SymbolRouteKind,
}

pub(crate) static CURRENT_LANGUAGE_POLICY: &[LanguagePolicy] = &[
    LanguagePolicy {
        public_mode: "rust",
        parser_support: ParserSupport::Native,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::BuiltIn,
    },
    LanguagePolicy {
        public_mode: "rust-build-script",
        parser_support: ParserSupport::Native,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::BuiltIn,
    },
    LanguagePolicy {
        public_mode: "python",
        parser_support: ParserSupport::Native,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::BuiltIn,
    },
    LanguagePolicy {
        public_mode: "javascript",
        parser_support: ParserSupport::Native,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::BuiltIn,
    },
    LanguagePolicy {
        public_mode: "typescript",
        parser_support: ParserSupport::Native,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::BuiltIn,
    },
    LanguagePolicy {
        public_mode: "tsx",
        parser_support: ParserSupport::Native,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::BuiltIn,
    },
    LanguagePolicy {
        public_mode: "java",
        parser_support: ParserSupport::Native,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::BuiltIn,
    },
    LanguagePolicy {
        public_mode: "kotlin",
        parser_support: ParserSupport::Native,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::BuiltIn,
    },
    LanguagePolicy {
        public_mode: "csharp",
        parser_support: ParserSupport::Native,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::BuiltIn,
    },
    LanguagePolicy {
        public_mode: "go",
        parser_support: ParserSupport::Native,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::BuiltIn,
    },
    LanguagePolicy {
        public_mode: "objective-c",
        parser_support: ParserSupport::Native,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::BuiltIn,
    },
    LanguagePolicy {
        public_mode: "zig",
        parser_support: ParserSupport::Native,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::BuiltIn,
    },
    LanguagePolicy {
        public_mode: "c",
        parser_support: ParserSupport::Native,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::BuiltIn,
    },
    LanguagePolicy {
        public_mode: "cpp",
        parser_support: ParserSupport::Native,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::BuiltIn,
    },
    LanguagePolicy {
        public_mode: "h",
        parser_support: ParserSupport::Native,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::BuiltIn,
    },
    LanguagePolicy {
        public_mode: "hpp",
        parser_support: ParserSupport::Native,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::BuiltIn,
    },
    LanguagePolicy {
        public_mode: "cargo-manifest",
        parser_support: ParserSupport::Manifest,
        summary_adapter: SummaryAdapter::Toml,
        symbol_route: SymbolRouteKind::Manifest,
    },
    LanguagePolicy {
        public_mode: "cargo-lock",
        parser_support: ParserSupport::Manifest,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Manifest,
    },
    LanguagePolicy {
        public_mode: "vue",
        parser_support: ParserSupport::Structural,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Structural,
    },
    LanguagePolicy {
        public_mode: "markdown",
        parser_support: ParserSupport::Structural,
        summary_adapter: SummaryAdapter::Markdown,
        symbol_route: SymbolRouteKind::Skip,
    },
    LanguagePolicy {
        public_mode: "json",
        parser_support: ParserSupport::Structural,
        summary_adapter: SummaryAdapter::Json,
        symbol_route: SymbolRouteKind::Skip,
    },
    LanguagePolicy {
        public_mode: "yaml",
        parser_support: ParserSupport::Structural,
        summary_adapter: SummaryAdapter::Yaml,
        symbol_route: SymbolRouteKind::Skip,
    },
    LanguagePolicy {
        public_mode: "css",
        parser_support: ParserSupport::Structural,
        summary_adapter: SummaryAdapter::Css,
        symbol_route: SymbolRouteKind::Skip,
    },
    LanguagePolicy {
        public_mode: "html",
        parser_support: ParserSupport::Structural,
        summary_adapter: SummaryAdapter::Html,
        symbol_route: SymbolRouteKind::Skip,
    },
    LanguagePolicy {
        public_mode: "toon",
        parser_support: ParserSupport::Structural,
        summary_adapter: SummaryAdapter::Toon,
        symbol_route: SymbolRouteKind::Skip,
    },
    LanguagePolicy {
        public_mode: "dockerfile",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "makefile",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "text",
        parser_support: ParserSupport::Structural,
        summary_adapter: SummaryAdapter::ConfigText,
        symbol_route: SymbolRouteKind::Skip,
    },
    LanguagePolicy {
        public_mode: "toml",
        parser_support: ParserSupport::Structural,
        summary_adapter: SummaryAdapter::Toml,
        symbol_route: SymbolRouteKind::Skip,
    },
    LanguagePolicy {
        public_mode: "xml",
        parser_support: ParserSupport::Structural,
        summary_adapter: SummaryAdapter::Xml,
        symbol_route: SymbolRouteKind::Skip,
    },
    LanguagePolicy {
        public_mode: "svelte",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "astro",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "jsp",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "jsp-tag",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "gsp",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "groovy",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "protobuf",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "handlebars",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "ejs",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "pug",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "freemarker",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "mustache",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "liquid",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "erb",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "sql",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "graphql",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "config",
        parser_support: ParserSupport::Structural,
        summary_adapter: SummaryAdapter::ConfigText,
        symbol_route: SymbolRouteKind::Skip,
    },
    LanguagePolicy {
        public_mode: "ruby",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "php",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "swift",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "scala",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "shell",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "powershell",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::PowerShell,
        symbol_route: SymbolRouteKind::Structural,
    },
    LanguagePolicy {
        public_mode: "batch",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "r",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "perl",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "lua",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "dart",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "haskell",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "ocaml",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "fsharp",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "clojure",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
    LanguagePolicy {
        public_mode: "vim",
        parser_support: ParserSupport::Fallback,
        summary_adapter: SummaryAdapter::None,
        symbol_route: SymbolRouteKind::Fallback,
    },
];

pub(crate) fn language_policy_for_public_mode(
    public_mode: &str,
) -> Option<&'static LanguagePolicy> {
    match public_mode {
        "rust" => Some(&CURRENT_LANGUAGE_POLICY[0]),
        "rust-build-script" => Some(&CURRENT_LANGUAGE_POLICY[1]),
        "python" => Some(&CURRENT_LANGUAGE_POLICY[2]),
        "javascript" => Some(&CURRENT_LANGUAGE_POLICY[3]),
        "typescript" => Some(&CURRENT_LANGUAGE_POLICY[4]),
        "tsx" => Some(&CURRENT_LANGUAGE_POLICY[5]),
        "java" => Some(&CURRENT_LANGUAGE_POLICY[6]),
        "kotlin" => Some(&CURRENT_LANGUAGE_POLICY[7]),
        "csharp" => Some(&CURRENT_LANGUAGE_POLICY[8]),
        "go" => Some(&CURRENT_LANGUAGE_POLICY[9]),
        "objective-c" => Some(&CURRENT_LANGUAGE_POLICY[10]),
        "zig" => Some(&CURRENT_LANGUAGE_POLICY[11]),
        "c" => Some(&CURRENT_LANGUAGE_POLICY[12]),
        "cpp" => Some(&CURRENT_LANGUAGE_POLICY[13]),
        "h" => Some(&CURRENT_LANGUAGE_POLICY[14]),
        "hpp" => Some(&CURRENT_LANGUAGE_POLICY[15]),
        "cargo-manifest" => Some(&CURRENT_LANGUAGE_POLICY[16]),
        "cargo-lock" => Some(&CURRENT_LANGUAGE_POLICY[17]),
        "vue" => Some(&CURRENT_LANGUAGE_POLICY[18]),
        "markdown" => Some(&CURRENT_LANGUAGE_POLICY[19]),
        "json" => Some(&CURRENT_LANGUAGE_POLICY[20]),
        "yaml" => Some(&CURRENT_LANGUAGE_POLICY[21]),
        "css" => Some(&CURRENT_LANGUAGE_POLICY[22]),
        "html" => Some(&CURRENT_LANGUAGE_POLICY[23]),
        "toon" => Some(&CURRENT_LANGUAGE_POLICY[24]),
        "dockerfile" => Some(&CURRENT_LANGUAGE_POLICY[25]),
        "makefile" => Some(&CURRENT_LANGUAGE_POLICY[26]),
        "text" => Some(&CURRENT_LANGUAGE_POLICY[27]),
        "toml" => Some(&CURRENT_LANGUAGE_POLICY[28]),
        "xml" => Some(&CURRENT_LANGUAGE_POLICY[29]),
        "svelte" => Some(&CURRENT_LANGUAGE_POLICY[30]),
        "astro" => Some(&CURRENT_LANGUAGE_POLICY[31]),
        "jsp" => Some(&CURRENT_LANGUAGE_POLICY[32]),
        "jsp-tag" => Some(&CURRENT_LANGUAGE_POLICY[33]),
        "gsp" => Some(&CURRENT_LANGUAGE_POLICY[34]),
        "groovy" => Some(&CURRENT_LANGUAGE_POLICY[35]),
        "protobuf" => Some(&CURRENT_LANGUAGE_POLICY[36]),
        "handlebars" => Some(&CURRENT_LANGUAGE_POLICY[37]),
        "ejs" => Some(&CURRENT_LANGUAGE_POLICY[38]),
        "pug" => Some(&CURRENT_LANGUAGE_POLICY[39]),
        "freemarker" => Some(&CURRENT_LANGUAGE_POLICY[40]),
        "mustache" => Some(&CURRENT_LANGUAGE_POLICY[41]),
        "liquid" => Some(&CURRENT_LANGUAGE_POLICY[42]),
        "erb" => Some(&CURRENT_LANGUAGE_POLICY[43]),
        "sql" => Some(&CURRENT_LANGUAGE_POLICY[44]),
        "graphql" => Some(&CURRENT_LANGUAGE_POLICY[45]),
        "config" => Some(&CURRENT_LANGUAGE_POLICY[46]),
        "ruby" => Some(&CURRENT_LANGUAGE_POLICY[47]),
        "php" => Some(&CURRENT_LANGUAGE_POLICY[48]),
        "swift" => Some(&CURRENT_LANGUAGE_POLICY[49]),
        "scala" => Some(&CURRENT_LANGUAGE_POLICY[50]),
        "shell" => Some(&CURRENT_LANGUAGE_POLICY[51]),
        "powershell" => Some(&CURRENT_LANGUAGE_POLICY[52]),
        "batch" => Some(&CURRENT_LANGUAGE_POLICY[53]),
        "r" => Some(&CURRENT_LANGUAGE_POLICY[54]),
        "perl" => Some(&CURRENT_LANGUAGE_POLICY[55]),
        "lua" => Some(&CURRENT_LANGUAGE_POLICY[56]),
        "dart" => Some(&CURRENT_LANGUAGE_POLICY[57]),
        "haskell" => Some(&CURRENT_LANGUAGE_POLICY[58]),
        "ocaml" => Some(&CURRENT_LANGUAGE_POLICY[59]),
        "fsharp" => Some(&CURRENT_LANGUAGE_POLICY[60]),
        "clojure" => Some(&CURRENT_LANGUAGE_POLICY[61]),
        "vim" => Some(&CURRENT_LANGUAGE_POLICY[62]),
        _ => None,
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum AcceptedAdvertisement {
    BlockedUntilAchievedManifest,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum CapabilityTier {
    Detected,
    Parsed,
    Symbols,
    Semantic,
    Benchmarked,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum PackOwnership {
    DefaultCore,
    Optional,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum PackRuntime {
    InProcess,
    SupervisedWorker,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct LanguageRegistrySettings {
    pub(crate) registry_id: &'static str,
    pub(crate) accepted_registry_id: &'static str,
    pub(crate) accepted_set_sha256: &'static str,
    pub(crate) accepted_advertisement: AcceptedAdvertisement,
    pub(crate) current_mode_count: usize,
    pub(crate) accepted_mode_count: usize,
    pub(crate) accepted_pre_parse_transform_count: usize,
    pub(crate) normalized_parser_capability_count: usize,
    pub(crate) parser_component_count: usize,
    pub(crate) parser_asset_count: usize,
    pub(crate) embedded_adapter_count: usize,
    pub(crate) query_pack_count: usize,
    pub(crate) semantic_provider_count: usize,
}

pub(crate) static LANGUAGE_REGISTRY_SETTINGS: LanguageRegistrySettings = LanguageRegistrySettings {
    registry_id: "registry.projectatlas-language-runtime",
    accepted_registry_id: "projectatlas-v0.4-candidate-215x209",
    accepted_set_sha256: "ed9d1012653830f9efabf2b678c8849e5372a1a8a8b390da4f764a53553e7512",
    accepted_advertisement: AcceptedAdvertisement::BlockedUntilAchievedManifest,
    current_mode_count: 63,
    accepted_mode_count: 215,
    accepted_pre_parse_transform_count: 1,
    normalized_parser_capability_count: 209,
    parser_component_count: 13,
    parser_asset_count: 0,
    embedded_adapter_count: 0,
    query_pack_count: 0,
    semantic_provider_count: 0,
};

pub(crate) static LANGUAGE_CAPABILITY_TIERS: &[CapabilityTier] = &[
    CapabilityTier::Detected,
    CapabilityTier::Parsed,
    CapabilityTier::Symbols,
    CapabilityTier::Semantic,
    CapabilityTier::Benchmarked,
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct LanguagePackSettings {
    pub(crate) pack_id: &'static str,
    pub(crate) ownership: PackOwnership,
    pub(crate) runtime: PackRuntime,
}

pub(crate) static LANGUAGE_PACK_SETTINGS: &[LanguagePackSettings] = &[
    LanguagePackSettings {
        pack_id: "default-core",
        ownership: PackOwnership::DefaultCore,
        runtime: PackRuntime::InProcess,
    },
    LanguagePackSettings {
        pack_id: "broad-language-pack",
        ownership: PackOwnership::Optional,
        runtime: PackRuntime::SupervisedWorker,
    },
    LanguagePackSettings {
        pack_id: "semantic-pack",
        ownership: PackOwnership::Optional,
        runtime: PackRuntime::SupervisedWorker,
    },
];

#[cfg(test)]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct EvaluationParserPackTrust {
    pub(crate) candidate_id: &'static str,
    pub(crate) eligibility: &'static str,
    pub(crate) pack_id: &'static str,
    pub(crate) release_version: &'static str,
    pub(crate) advertised: bool,
    pub(crate) pack_abi_id: &'static str,
    pub(crate) pack_abi_version: u32,
    pub(crate) grammar_abi_id: &'static str,
    pub(crate) grammar_abi_version: u32,
    pub(crate) grammar_abi_state: &'static str,
    pub(crate) packaged_platform: &'static str,
    pub(crate) payload_root: &'static str,
    pub(crate) manifest_path: &'static str,
    pub(crate) installed_bytes: u64,
    pub(crate) installed_byte_limit: u64,
}

#[cfg(test)]
pub(crate) static EVALUATION_PARSER_PACK_TRUST: &[EvaluationParserPackTrust] =
    &[EvaluationParserPackTrust {
        candidate_id: "tree-sitter-wasm-grammar-pack",
        eligibility: "evaluation-only-unselected",
        pack_id: "broad-language-pack",
        release_version: "tree-sitter-javascript-0.25.0-wasm",
        advertised: false,
        pack_abi_id: "abi.projectatlas-parser-pack",
        pack_abi_version: 1,
        grammar_abi_id: "abi.tree-sitter-wasm",
        grammar_abi_version: 15,
        grammar_abi_state: "pending-pack-verification",
        packaged_platform: "wasm32-unknown-emscripten",
        payload_root: "fixtures/parser-packs/tree-sitter-wasm-grammar-pack",
        manifest_path: "manifest.json",
        installed_bytes: 427_948,
        installed_byte_limit: 805_306_368,
    }];
