// @generated by `cargo projectatlas-lints language-registry write`; do not edit.
//! Generated symbols routing language-registry projection.

pub(crate) const LANGUAGE_REGISTRY_SOURCE_LOCK_SHA256: &str =
    "66938d6649fed6dd54a8bd18d60123104c4e116ce90aec2a9b56b7c70166d477";
pub(crate) const LANGUAGE_REGISTRY_CONTRACT_SHA256: &str =
    "3654ffb023ca1621a71d84dc229869e340f5a23b65a90ab016df9bceaf9625d6";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum BuiltInParser {
    Rust,
    Python,
    JavaScript,
    TypeScript,
    Tsx,
    Java,
    Kotlin,
    CSharp,
    Go,
    ObjectiveC,
    Zig,
    C,
    Cpp,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum ManifestAdapter {
    CargoManifest,
    CargoLock,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum StructuralAdapter {
    Vue,
    PowerShell,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum SymbolAugmenter {
    Kotlin,
    GradleKotlin,
    ObjectiveC,
    Zig,
    GradleGroovy,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum SymbolRoute {
    Skip,
    BuiltIn {
        parser: BuiltInParser,
        augmenters: &'static [SymbolAugmenter],
    },
    Manifest(ManifestAdapter),
    Structural(StructuralAdapter),
    Fallback {
        augmenters: &'static [SymbolAugmenter],
    },
}

impl SymbolRoute {
    pub(crate) const fn augmenters(&self) -> &'static [SymbolAugmenter] {
        match self {
            Self::BuiltIn { augmenters, .. } | Self::Fallback { augmenters, .. } => augmenters,
            Self::Skip | Self::Manifest(_) | Self::Structural(_) => &[],
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct LanguageSymbolRoute {
    pub(crate) public_mode: &'static str,
    pub(crate) route: SymbolRoute,
}

pub(crate) static CURRENT_SYMBOL_ROUTES: &[LanguageSymbolRoute] = &[
    LanguageSymbolRoute {
        public_mode: "rust",
        route: SymbolRoute::BuiltIn {
            parser: BuiltInParser::Rust,
            augmenters: &[],
        },
    },
    LanguageSymbolRoute {
        public_mode: "rust-build-script",
        route: SymbolRoute::BuiltIn {
            parser: BuiltInParser::Rust,
            augmenters: &[],
        },
    },
    LanguageSymbolRoute {
        public_mode: "python",
        route: SymbolRoute::BuiltIn {
            parser: BuiltInParser::Python,
            augmenters: &[],
        },
    },
    LanguageSymbolRoute {
        public_mode: "javascript",
        route: SymbolRoute::BuiltIn {
            parser: BuiltInParser::JavaScript,
            augmenters: &[],
        },
    },
    LanguageSymbolRoute {
        public_mode: "typescript",
        route: SymbolRoute::BuiltIn {
            parser: BuiltInParser::TypeScript,
            augmenters: &[],
        },
    },
    LanguageSymbolRoute {
        public_mode: "tsx",
        route: SymbolRoute::BuiltIn {
            parser: BuiltInParser::Tsx,
            augmenters: &[],
        },
    },
    LanguageSymbolRoute {
        public_mode: "java",
        route: SymbolRoute::BuiltIn {
            parser: BuiltInParser::Java,
            augmenters: &[],
        },
    },
    LanguageSymbolRoute {
        public_mode: "kotlin",
        route: SymbolRoute::BuiltIn {
            parser: BuiltInParser::Kotlin,
            augmenters: &[SymbolAugmenter::Kotlin, SymbolAugmenter::GradleKotlin],
        },
    },
    LanguageSymbolRoute {
        public_mode: "csharp",
        route: SymbolRoute::BuiltIn {
            parser: BuiltInParser::CSharp,
            augmenters: &[],
        },
    },
    LanguageSymbolRoute {
        public_mode: "go",
        route: SymbolRoute::BuiltIn {
            parser: BuiltInParser::Go,
            augmenters: &[],
        },
    },
    LanguageSymbolRoute {
        public_mode: "objective-c",
        route: SymbolRoute::BuiltIn {
            parser: BuiltInParser::ObjectiveC,
            augmenters: &[SymbolAugmenter::ObjectiveC],
        },
    },
    LanguageSymbolRoute {
        public_mode: "zig",
        route: SymbolRoute::BuiltIn {
            parser: BuiltInParser::Zig,
            augmenters: &[SymbolAugmenter::Zig],
        },
    },
    LanguageSymbolRoute {
        public_mode: "c",
        route: SymbolRoute::BuiltIn {
            parser: BuiltInParser::C,
            augmenters: &[],
        },
    },
    LanguageSymbolRoute {
        public_mode: "cpp",
        route: SymbolRoute::BuiltIn {
            parser: BuiltInParser::Cpp,
            augmenters: &[],
        },
    },
    LanguageSymbolRoute {
        public_mode: "h",
        route: SymbolRoute::BuiltIn {
            parser: BuiltInParser::C,
            augmenters: &[],
        },
    },
    LanguageSymbolRoute {
        public_mode: "hpp",
        route: SymbolRoute::BuiltIn {
            parser: BuiltInParser::Cpp,
            augmenters: &[],
        },
    },
    LanguageSymbolRoute {
        public_mode: "cargo-manifest",
        route: SymbolRoute::Manifest(ManifestAdapter::CargoManifest),
    },
    LanguageSymbolRoute {
        public_mode: "cargo-lock",
        route: SymbolRoute::Manifest(ManifestAdapter::CargoLock),
    },
    LanguageSymbolRoute {
        public_mode: "vue",
        route: SymbolRoute::Structural(StructuralAdapter::Vue),
    },
    LanguageSymbolRoute {
        public_mode: "markdown",
        route: SymbolRoute::Skip,
    },
    LanguageSymbolRoute {
        public_mode: "json",
        route: SymbolRoute::Skip,
    },
    LanguageSymbolRoute {
        public_mode: "yaml",
        route: SymbolRoute::Skip,
    },
    LanguageSymbolRoute {
        public_mode: "css",
        route: SymbolRoute::Skip,
    },
    LanguageSymbolRoute {
        public_mode: "html",
        route: SymbolRoute::Skip,
    },
    LanguageSymbolRoute {
        public_mode: "toon",
        route: SymbolRoute::Skip,
    },
    LanguageSymbolRoute {
        public_mode: "dockerfile",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "makefile",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "text",
        route: SymbolRoute::Skip,
    },
    LanguageSymbolRoute {
        public_mode: "toml",
        route: SymbolRoute::Skip,
    },
    LanguageSymbolRoute {
        public_mode: "xml",
        route: SymbolRoute::Skip,
    },
    LanguageSymbolRoute {
        public_mode: "svelte",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "astro",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "jsp",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "jsp-tag",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "gsp",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "groovy",
        route: SymbolRoute::Fallback {
            augmenters: &[SymbolAugmenter::GradleGroovy],
        },
    },
    LanguageSymbolRoute {
        public_mode: "protobuf",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "handlebars",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "ejs",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "pug",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "freemarker",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "mustache",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "liquid",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "erb",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "sql",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "graphql",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "config",
        route: SymbolRoute::Skip,
    },
    LanguageSymbolRoute {
        public_mode: "ruby",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "php",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "swift",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "scala",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "shell",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "powershell",
        route: SymbolRoute::Structural(StructuralAdapter::PowerShell),
    },
    LanguageSymbolRoute {
        public_mode: "batch",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "r",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "perl",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "lua",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "dart",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "haskell",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "ocaml",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "fsharp",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "clojure",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
    LanguageSymbolRoute {
        public_mode: "vim",
        route: SymbolRoute::Fallback { augmenters: &[] },
    },
];

pub(crate) fn symbol_route_for_public_mode(public_mode: &str) -> Option<&'static SymbolRoute> {
    match public_mode {
        "rust" => Some(&CURRENT_SYMBOL_ROUTES[0].route),
        "rust-build-script" => Some(&CURRENT_SYMBOL_ROUTES[1].route),
        "python" => Some(&CURRENT_SYMBOL_ROUTES[2].route),
        "javascript" => Some(&CURRENT_SYMBOL_ROUTES[3].route),
        "typescript" => Some(&CURRENT_SYMBOL_ROUTES[4].route),
        "tsx" => Some(&CURRENT_SYMBOL_ROUTES[5].route),
        "java" => Some(&CURRENT_SYMBOL_ROUTES[6].route),
        "kotlin" => Some(&CURRENT_SYMBOL_ROUTES[7].route),
        "csharp" => Some(&CURRENT_SYMBOL_ROUTES[8].route),
        "go" => Some(&CURRENT_SYMBOL_ROUTES[9].route),
        "objective-c" => Some(&CURRENT_SYMBOL_ROUTES[10].route),
        "zig" => Some(&CURRENT_SYMBOL_ROUTES[11].route),
        "c" => Some(&CURRENT_SYMBOL_ROUTES[12].route),
        "cpp" => Some(&CURRENT_SYMBOL_ROUTES[13].route),
        "h" => Some(&CURRENT_SYMBOL_ROUTES[14].route),
        "hpp" => Some(&CURRENT_SYMBOL_ROUTES[15].route),
        "cargo-manifest" => Some(&CURRENT_SYMBOL_ROUTES[16].route),
        "cargo-lock" => Some(&CURRENT_SYMBOL_ROUTES[17].route),
        "vue" => Some(&CURRENT_SYMBOL_ROUTES[18].route),
        "markdown" => Some(&CURRENT_SYMBOL_ROUTES[19].route),
        "json" => Some(&CURRENT_SYMBOL_ROUTES[20].route),
        "yaml" => Some(&CURRENT_SYMBOL_ROUTES[21].route),
        "css" => Some(&CURRENT_SYMBOL_ROUTES[22].route),
        "html" => Some(&CURRENT_SYMBOL_ROUTES[23].route),
        "toon" => Some(&CURRENT_SYMBOL_ROUTES[24].route),
        "dockerfile" => Some(&CURRENT_SYMBOL_ROUTES[25].route),
        "makefile" => Some(&CURRENT_SYMBOL_ROUTES[26].route),
        "text" => Some(&CURRENT_SYMBOL_ROUTES[27].route),
        "toml" => Some(&CURRENT_SYMBOL_ROUTES[28].route),
        "xml" => Some(&CURRENT_SYMBOL_ROUTES[29].route),
        "svelte" => Some(&CURRENT_SYMBOL_ROUTES[30].route),
        "astro" => Some(&CURRENT_SYMBOL_ROUTES[31].route),
        "jsp" => Some(&CURRENT_SYMBOL_ROUTES[32].route),
        "jsp-tag" => Some(&CURRENT_SYMBOL_ROUTES[33].route),
        "gsp" => Some(&CURRENT_SYMBOL_ROUTES[34].route),
        "groovy" => Some(&CURRENT_SYMBOL_ROUTES[35].route),
        "protobuf" => Some(&CURRENT_SYMBOL_ROUTES[36].route),
        "handlebars" => Some(&CURRENT_SYMBOL_ROUTES[37].route),
        "ejs" => Some(&CURRENT_SYMBOL_ROUTES[38].route),
        "pug" => Some(&CURRENT_SYMBOL_ROUTES[39].route),
        "freemarker" => Some(&CURRENT_SYMBOL_ROUTES[40].route),
        "mustache" => Some(&CURRENT_SYMBOL_ROUTES[41].route),
        "liquid" => Some(&CURRENT_SYMBOL_ROUTES[42].route),
        "erb" => Some(&CURRENT_SYMBOL_ROUTES[43].route),
        "sql" => Some(&CURRENT_SYMBOL_ROUTES[44].route),
        "graphql" => Some(&CURRENT_SYMBOL_ROUTES[45].route),
        "config" => Some(&CURRENT_SYMBOL_ROUTES[46].route),
        "ruby" => Some(&CURRENT_SYMBOL_ROUTES[47].route),
        "php" => Some(&CURRENT_SYMBOL_ROUTES[48].route),
        "swift" => Some(&CURRENT_SYMBOL_ROUTES[49].route),
        "scala" => Some(&CURRENT_SYMBOL_ROUTES[50].route),
        "shell" => Some(&CURRENT_SYMBOL_ROUTES[51].route),
        "powershell" => Some(&CURRENT_SYMBOL_ROUTES[52].route),
        "batch" => Some(&CURRENT_SYMBOL_ROUTES[53].route),
        "r" => Some(&CURRENT_SYMBOL_ROUTES[54].route),
        "perl" => Some(&CURRENT_SYMBOL_ROUTES[55].route),
        "lua" => Some(&CURRENT_SYMBOL_ROUTES[56].route),
        "dart" => Some(&CURRENT_SYMBOL_ROUTES[57].route),
        "haskell" => Some(&CURRENT_SYMBOL_ROUTES[58].route),
        "ocaml" => Some(&CURRENT_SYMBOL_ROUTES[59].route),
        "fsharp" => Some(&CURRENT_SYMBOL_ROUTES[60].route),
        "clojure" => Some(&CURRENT_SYMBOL_ROUTES[61].route),
        "vim" => Some(&CURRENT_SYMBOL_ROUTES[62].route),
        _ => None,
    }
}

pub(crate) static SPECIALIZED_LANGUAGES: &[&str] = &[
    "rust",
    "rust-build-script",
    "python",
    "javascript",
    "typescript",
    "tsx",
    "java",
    "kotlin",
    "csharp",
    "go",
    "objective-c",
    "zig",
    "c",
    "cpp",
    "h",
    "hpp",
];

pub(crate) fn built_in_parser_for_public_mode(public_mode: &str) -> Option<BuiltInParser> {
    match symbol_route_for_public_mode(public_mode)? {
        SymbolRoute::BuiltIn { parser, .. } => Some(*parser),
        SymbolRoute::Skip
        | SymbolRoute::Manifest(_)
        | SymbolRoute::Structural(_)
        | SymbolRoute::Fallback { .. } => None,
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum ParserImplementation {
    CompiledTreeSitter,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum ParserAbiState {
    CurrentCompiledContract,
    PendingPackVerification,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct ParserComponentContract {
    pub(crate) parser_id: &'static str,
    pub(crate) built_in_parser: BuiltInParser,
    pub(crate) implementation: ParserImplementation,
    pub(crate) current_pack_id: &'static str,
    pub(crate) abi_id: &'static str,
    pub(crate) abi_version: u32,
    pub(crate) abi_state: ParserAbiState,
    pub(crate) asset_id: Option<&'static str>,
    pub(crate) query_pack_id: Option<&'static str>,
    pub(crate) fixture_ids: &'static [&'static str],
    pub(crate) provenance_evidence_ids: &'static [&'static str],
}

pub(crate) static CURRENT_PARSER_COMPONENTS: &[ParserComponentContract] = &[
    ParserComponentContract {
        parser_id: "parser.builtin.rust",
        built_in_parser: BuiltInParser::Rust,
        implementation: ParserImplementation::CompiledTreeSitter,
        current_pack_id: "default-core",
        abi_id: "abi.projectatlas-compiled-parser",
        abi_version: 1,
        abi_state: ParserAbiState::CurrentCompiledContract,
        asset_id: None,
        query_pack_id: None,
        fixture_ids: &["fixture.historical-runtime-contract"],
        provenance_evidence_ids: &["evidence.historical-runtime-contract"],
    },
    ParserComponentContract {
        parser_id: "parser.builtin.python",
        built_in_parser: BuiltInParser::Python,
        implementation: ParserImplementation::CompiledTreeSitter,
        current_pack_id: "default-core",
        abi_id: "abi.projectatlas-compiled-parser",
        abi_version: 1,
        abi_state: ParserAbiState::CurrentCompiledContract,
        asset_id: None,
        query_pack_id: None,
        fixture_ids: &["fixture.historical-runtime-contract"],
        provenance_evidence_ids: &["evidence.historical-runtime-contract"],
    },
    ParserComponentContract {
        parser_id: "parser.builtin.javascript",
        built_in_parser: BuiltInParser::JavaScript,
        implementation: ParserImplementation::CompiledTreeSitter,
        current_pack_id: "default-core",
        abi_id: "abi.projectatlas-compiled-parser",
        abi_version: 1,
        abi_state: ParserAbiState::CurrentCompiledContract,
        asset_id: None,
        query_pack_id: None,
        fixture_ids: &["fixture.historical-runtime-contract"],
        provenance_evidence_ids: &["evidence.historical-runtime-contract"],
    },
    ParserComponentContract {
        parser_id: "parser.builtin.typescript",
        built_in_parser: BuiltInParser::TypeScript,
        implementation: ParserImplementation::CompiledTreeSitter,
        current_pack_id: "default-core",
        abi_id: "abi.projectatlas-compiled-parser",
        abi_version: 1,
        abi_state: ParserAbiState::CurrentCompiledContract,
        asset_id: None,
        query_pack_id: None,
        fixture_ids: &["fixture.historical-runtime-contract"],
        provenance_evidence_ids: &["evidence.historical-runtime-contract"],
    },
    ParserComponentContract {
        parser_id: "parser.builtin.tsx",
        built_in_parser: BuiltInParser::Tsx,
        implementation: ParserImplementation::CompiledTreeSitter,
        current_pack_id: "default-core",
        abi_id: "abi.projectatlas-compiled-parser",
        abi_version: 1,
        abi_state: ParserAbiState::CurrentCompiledContract,
        asset_id: None,
        query_pack_id: None,
        fixture_ids: &["fixture.historical-runtime-contract"],
        provenance_evidence_ids: &["evidence.historical-runtime-contract"],
    },
    ParserComponentContract {
        parser_id: "parser.builtin.java",
        built_in_parser: BuiltInParser::Java,
        implementation: ParserImplementation::CompiledTreeSitter,
        current_pack_id: "default-core",
        abi_id: "abi.projectatlas-compiled-parser",
        abi_version: 1,
        abi_state: ParserAbiState::CurrentCompiledContract,
        asset_id: None,
        query_pack_id: None,
        fixture_ids: &["fixture.historical-runtime-contract"],
        provenance_evidence_ids: &["evidence.historical-runtime-contract"],
    },
    ParserComponentContract {
        parser_id: "parser.builtin.kotlin",
        built_in_parser: BuiltInParser::Kotlin,
        implementation: ParserImplementation::CompiledTreeSitter,
        current_pack_id: "default-core",
        abi_id: "abi.projectatlas-compiled-parser",
        abi_version: 1,
        abi_state: ParserAbiState::CurrentCompiledContract,
        asset_id: None,
        query_pack_id: None,
        fixture_ids: &["fixture.historical-runtime-contract"],
        provenance_evidence_ids: &["evidence.historical-runtime-contract"],
    },
    ParserComponentContract {
        parser_id: "parser.builtin.csharp",
        built_in_parser: BuiltInParser::CSharp,
        implementation: ParserImplementation::CompiledTreeSitter,
        current_pack_id: "default-core",
        abi_id: "abi.projectatlas-compiled-parser",
        abi_version: 1,
        abi_state: ParserAbiState::CurrentCompiledContract,
        asset_id: None,
        query_pack_id: None,
        fixture_ids: &["fixture.historical-runtime-contract"],
        provenance_evidence_ids: &["evidence.historical-runtime-contract"],
    },
    ParserComponentContract {
        parser_id: "parser.builtin.go",
        built_in_parser: BuiltInParser::Go,
        implementation: ParserImplementation::CompiledTreeSitter,
        current_pack_id: "default-core",
        abi_id: "abi.projectatlas-compiled-parser",
        abi_version: 1,
        abi_state: ParserAbiState::CurrentCompiledContract,
        asset_id: None,
        query_pack_id: None,
        fixture_ids: &["fixture.historical-runtime-contract"],
        provenance_evidence_ids: &["evidence.historical-runtime-contract"],
    },
    ParserComponentContract {
        parser_id: "parser.builtin.objective-c",
        built_in_parser: BuiltInParser::ObjectiveC,
        implementation: ParserImplementation::CompiledTreeSitter,
        current_pack_id: "default-core",
        abi_id: "abi.projectatlas-compiled-parser",
        abi_version: 1,
        abi_state: ParserAbiState::CurrentCompiledContract,
        asset_id: None,
        query_pack_id: None,
        fixture_ids: &["fixture.historical-runtime-contract"],
        provenance_evidence_ids: &["evidence.historical-runtime-contract"],
    },
    ParserComponentContract {
        parser_id: "parser.builtin.zig",
        built_in_parser: BuiltInParser::Zig,
        implementation: ParserImplementation::CompiledTreeSitter,
        current_pack_id: "default-core",
        abi_id: "abi.projectatlas-compiled-parser",
        abi_version: 1,
        abi_state: ParserAbiState::CurrentCompiledContract,
        asset_id: None,
        query_pack_id: None,
        fixture_ids: &["fixture.historical-runtime-contract"],
        provenance_evidence_ids: &["evidence.historical-runtime-contract"],
    },
    ParserComponentContract {
        parser_id: "parser.builtin.c",
        built_in_parser: BuiltInParser::C,
        implementation: ParserImplementation::CompiledTreeSitter,
        current_pack_id: "default-core",
        abi_id: "abi.projectatlas-compiled-parser",
        abi_version: 1,
        abi_state: ParserAbiState::CurrentCompiledContract,
        asset_id: None,
        query_pack_id: None,
        fixture_ids: &["fixture.historical-runtime-contract"],
        provenance_evidence_ids: &["evidence.historical-runtime-contract"],
    },
    ParserComponentContract {
        parser_id: "parser.builtin.cpp",
        built_in_parser: BuiltInParser::Cpp,
        implementation: ParserImplementation::CompiledTreeSitter,
        current_pack_id: "default-core",
        abi_id: "abi.projectatlas-compiled-parser",
        abi_version: 1,
        abi_state: ParserAbiState::CurrentCompiledContract,
        asset_id: None,
        query_pack_id: None,
        fixture_ids: &["fixture.historical-runtime-contract"],
        provenance_evidence_ids: &["evidence.historical-runtime-contract"],
    },
];

pub(crate) const fn parser_component_id(parser: BuiltInParser) -> &'static str {
    match parser {
        BuiltInParser::Rust => "parser.builtin.rust",
        BuiltInParser::Python => "parser.builtin.python",
        BuiltInParser::JavaScript => "parser.builtin.javascript",
        BuiltInParser::TypeScript => "parser.builtin.typescript",
        BuiltInParser::Tsx => "parser.builtin.tsx",
        BuiltInParser::Java => "parser.builtin.java",
        BuiltInParser::Kotlin => "parser.builtin.kotlin",
        BuiltInParser::CSharp => "parser.builtin.csharp",
        BuiltInParser::Go => "parser.builtin.go",
        BuiltInParser::ObjectiveC => "parser.builtin.objective-c",
        BuiltInParser::Zig => "parser.builtin.zig",
        BuiltInParser::C => "parser.builtin.c",
        BuiltInParser::Cpp => "parser.builtin.cpp",
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct EmbeddedLanguageAdapter {
    pub(crate) adapter_id: &'static str,
    pub(crate) host_mode_id: &'static str,
    pub(crate) embedded_mode_id: &'static str,
    pub(crate) pack_id: &'static str,
    pub(crate) query_pack_id: Option<&'static str>,
    pub(crate) fixture_ids: &'static [&'static str],
}

pub(crate) static EMBEDDED_LANGUAGE_ADAPTERS: &[EmbeddedLanguageAdapter] = &[];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct ExtractionQueryPack {
    pub(crate) query_pack_id: &'static str,
    pub(crate) path: &'static str,
    pub(crate) pack_id: &'static str,
    pub(crate) digest_sha256: &'static str,
}

pub(crate) static EXTRACTION_QUERY_PACKS: &[ExtractionQueryPack] = &[];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct SemanticProviderContract {
    pub(crate) provider_id: &'static str,
    pub(crate) pack_id: &'static str,
    pub(crate) mode_ids: &'static [&'static str],
    pub(crate) fixture_ids: &'static [&'static str],
}

pub(crate) static SEMANTIC_PROVIDERS: &[SemanticProviderContract] = &[];
