"""
Purpose: Generate Markdown API docs for ProjectAtlas modules.
"""

from __future__ import annotations

import ast
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = ROOT / "src" / "projectatlas"
OUTPUT_PATH = ROOT / "docs" / "api.md"


def iter_python_files(root: Path) -> list[Path]:
    """Collect Python modules to document."""
    return sorted(path for path in root.rglob("*.py") if path.is_file())


def format_docstring(text: str | None) -> str:
    """Normalize a docstring for Markdown output."""
    if not text:
        return "_No docstring provided._"
    return text.strip().replace("\n", "\n    ")


def render_module(path: Path, root: Path) -> str:
    """Render a module section as Markdown."""
    module = ast.parse(path.read_text(encoding="utf-8"))
    rel = path.relative_to(root).as_posix()
    lines = [f"## `{rel}`", "", format_docstring(ast.get_docstring(module)), ""]
    for node in module.body:
        if isinstance(node, ast.ClassDef):
            lines.extend(render_class(node))
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            lines.extend(render_function(node))
    return "\n".join(lines)


def render_class(node: ast.ClassDef) -> list[str]:
    """Render a class section."""
    lines = [f"### Class `{node.name}`", "", format_docstring(ast.get_docstring(node)), ""]
    for member in node.body:
        if isinstance(member, (ast.FunctionDef, ast.AsyncFunctionDef)):
            lines.extend(render_method(member, node.name))
    return lines


def render_method(node: ast.AST, class_name: str) -> list[str]:
    """Render a method section."""
    name = node.name if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) else ""
    docstring = ast.get_docstring(node)
    return [
        f"#### `{class_name}.{name}`",
        "",
        format_docstring(docstring),
        "",
    ]


def render_function(node: ast.AST) -> list[str]:
    """Render a function section."""
    name = node.name if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) else ""
    docstring = ast.get_docstring(node)
    return [
        f"### Function `{name}`",
        "",
        format_docstring(docstring),
        "",
    ]


def build_docs() -> str:
    """Build the full API documentation Markdown."""
    sections = [
        "# ProjectAtlas API",
        "",
        "This document is generated by `scripts/generate_api_docs.py`.",
        "",
    ]
    for file_path in iter_python_files(SOURCE_ROOT):
        sections.append(render_module(file_path, SOURCE_ROOT))
    return "\n".join(sections).rstrip() + "\n"


def main() -> int:
    """Generate the API documentation file."""
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(build_docs(), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
