//! Purpose: Define `ProjectAtlas` 3 core domain models and shared helpers.

pub mod health;
pub mod language;
pub mod outline;
pub mod symbols;
pub mod telemetry;
pub mod toon;

use serde::{Deserialize, Serialize};
use std::fmt;
use std::path::{Path, PathBuf, StripPrefixError};
use thiserror::Error;

/// Core error type for `ProjectAtlas` domain operations.
#[derive(Debug, Error)]
pub enum CoreError {
    /// A path could not be represented relative to the repository root.
    #[error("path is outside the repository root: {path}")]
    PathOutsideRoot {
        /// Path that failed normalization.
        path: PathBuf,
        /// Original path-strip error.
        source: StripPrefixError,
    },
    /// A path contains non-UTF-8 data and cannot be stored in the index.
    #[error("path is not valid UTF-8: {path:?}")]
    NonUtf8Path {
        /// Path that could not be converted to UTF-8.
        path: PathBuf,
    },
    /// A user supplied path is not a safe repository-relative file key.
    #[error("path {path:?} must be a project-relative indexed file path: {reason}")]
    InvalidRepositoryPath {
        /// Invalid path.
        path: PathBuf,
        /// Human-readable validation reason.
        reason: &'static str,
    },
}

/// Convenient result alias for `ProjectAtlas` core operations.
pub type CoreResult<T> = Result<T, CoreError>;

/// File or folder node kind.
#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, PartialEq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum NodeKind {
    /// Directory node.
    Folder,
    /// File node.
    File,
}

impl fmt::Display for NodeKind {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Folder => formatter.write_str("folder"),
            Self::File => formatter.write_str("file"),
        }
    }
}

impl NodeKind {
    /// Parse a database string into a node kind.
    #[must_use]
    pub fn from_db(value: &str) -> Option<Self> {
        match value {
            "folder" => Some(Self::Folder),
            "file" => Some(Self::File),
            _ => None,
        }
    }
}

/// Status for purpose metadata.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum PurposeStatus {
    /// No purpose exists for this node yet.
    Missing,
    /// A generated or heuristic purpose exists but has not been approved.
    Suggested,
    /// A purpose has been explicitly approved.
    Approved,
    /// The node changed enough that the purpose should be reviewed.
    Stale,
}

impl fmt::Display for PurposeStatus {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Missing => formatter.write_str("missing"),
            Self::Suggested => formatter.write_str("suggested"),
            Self::Approved => formatter.write_str("approved"),
            Self::Stale => formatter.write_str("stale"),
        }
    }
}

impl PurposeStatus {
    /// Parse a database string into a purpose status.
    #[must_use]
    pub fn from_db(value: &str) -> Option<Self> {
        match value {
            "missing" => Some(Self::Missing),
            "suggested" => Some(Self::Suggested),
            "approved" => Some(Self::Approved),
            "stale" => Some(Self::Stale),
            _ => None,
        }
    }
}

/// Source for purpose metadata.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum PurposeSource {
    /// No source is known yet.
    Missing,
    /// Imported from legacy metadata such as `.purpose` or Purpose headers.
    Imported,
    /// Generated by a heuristic.
    Generated,
    /// Suggested by an agent or model.
    Agent,
    /// Explicitly supplied by a human.
    Human,
}

impl fmt::Display for PurposeSource {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Missing => formatter.write_str("missing"),
            Self::Imported => formatter.write_str("imported"),
            Self::Generated => formatter.write_str("generated"),
            Self::Agent => formatter.write_str("agent"),
            Self::Human => formatter.write_str("human"),
        }
    }
}

/// Repository node stored in the `ProjectAtlas` index.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct Node {
    /// Repository-relative path using forward slashes.
    pub path: String,
    /// File or folder kind.
    pub kind: NodeKind,
    /// Parent path using forward slashes.
    pub parent_path: Option<String>,
    /// File extension, including the dot.
    pub extension: Option<String>,
    /// Detected language or file family.
    pub language: Option<String>,
    /// File size in bytes.
    pub size_bytes: Option<u64>,
    /// File modification timestamp in nanoseconds since Unix epoch.
    pub mtime_ns: Option<i64>,
    /// BLAKE3 hash for file content.
    pub content_hash: Option<String>,
}

/// Purpose metadata attached to a node.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct Purpose {
    /// Repository-relative node path.
    pub path: String,
    /// Purpose one-liner.
    pub purpose: Option<String>,
    /// Purpose source.
    pub source: PurposeSource,
    /// Purpose lifecycle status.
    pub status: PurposeStatus,
}

/// A node with attached purpose state.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct IndexedNode {
    /// Node metadata.
    pub node: Node,
    /// Purpose metadata.
    pub purpose: Purpose,
    /// One-line observed content summary for this node.
    pub summary: Option<String>,
}

/// Overview returned by startup/overview commands.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct Overview {
    /// Number of indexed files.
    pub files: usize,
    /// Number of indexed folders.
    pub folders: usize,
    /// Number of missing purpose entries.
    pub missing_purposes: usize,
    /// Number of stale purpose entries.
    pub stale_purposes: usize,
    /// Number of approved purpose entries.
    pub approved_purposes: usize,
    /// Number of suggested purpose entries.
    pub suggested_purposes: usize,
}

/// Convert an absolute path into a stable repository-relative slash path.
///
/// # Errors
///
/// Returns an error when `path` is outside `root` or cannot be represented as
/// UTF-8.
pub fn normalize_repo_path(root: &Path, path: &Path) -> CoreResult<String> {
    let relative = path
        .strip_prefix(root)
        .map_err(|source| CoreError::PathOutsideRoot {
            path: path.to_path_buf(),
            source,
        })?;
    if relative.as_os_str().is_empty() {
        return Ok(".".to_string());
    }
    let as_str = relative.to_str().ok_or_else(|| CoreError::NonUtf8Path {
        path: relative.to_path_buf(),
    })?;
    Ok(as_str.replace('\\', "/"))
}

/// Normalize a native filesystem path for stable diagnostics and metadata.
///
/// The returned path uses forward slashes, strips Windows extended path
/// prefixes such as `\\?\`, and converts extended UNC paths to `//server/share`
/// form. This helper is for persisted metadata and agent-facing output; use
/// `Path`/`PathBuf` for host filesystem access.
#[must_use]
pub fn normalize_native_path_display(path: impl AsRef<Path>) -> String {
    normalize_native_path_display_str(&path.as_ref().to_string_lossy())
}

/// Normalize a native filesystem path string for stable diagnostics and metadata.
///
/// This string-oriented variant exists for values read from metadata or tests
/// before they are converted back into a platform `Path`.
#[must_use]
pub fn normalize_native_path_display_str(path: &str) -> String {
    let normalized = path.replace('\\', "/");
    if let Some(rest) = normalized.strip_prefix("//?/UNC/") {
        format!("//{rest}")
    } else if let Some(rest) = normalized.strip_prefix("//?/") {
        rest.to_string()
    } else {
        normalized
    }
}

/// Normalize and validate a user-supplied path as a repository-relative file key.
///
/// # Errors
///
/// Returns an error when `file` is absolute, uses a Windows drive prefix,
/// contains parent traversal, is empty, or cannot be represented as UTF-8.
pub fn validated_repo_file_key(file: &Path) -> CoreResult<String> {
    let raw = file
        .to_str()
        .ok_or_else(|| CoreError::NonUtf8Path {
            path: file.to_path_buf(),
        })?
        .replace('\\', "/");
    if raw.starts_with('/') || raw.starts_with("//") || has_windows_drive_prefix(&raw) {
        return Err(CoreError::InvalidRepositoryPath {
            path: file.to_path_buf(),
            reason: "absolute paths are not allowed",
        });
    }
    let mut parts = Vec::new();
    for component in raw.split('/') {
        match component {
            "" | "." => {}
            ".." => {
                return Err(CoreError::InvalidRepositoryPath {
                    path: file.to_path_buf(),
                    reason: "parent traversal is not allowed",
                });
            }
            part => parts.push(part.to_string()),
        }
    }
    if parts.is_empty() {
        return Err(CoreError::InvalidRepositoryPath {
            path: file.to_path_buf(),
            reason: "a file path is required",
        });
    }
    Ok(parts.join("/"))
}

/// Convert a stable slash-separated repository key into a native path.
#[must_use]
pub fn repo_path_to_native(path: &str) -> PathBuf {
    path.split('/').fold(PathBuf::new(), |mut native, part| {
        native.push(part);
        native
    })
}

/// Return whether normalized text starts with a Windows drive prefix.
fn has_windows_drive_prefix(path: &str) -> bool {
    let bytes = path.as_bytes();
    bytes.len() >= 2 && bytes[1] == b':' && bytes[0].is_ascii_alphabetic()
}

/// Return the parent path for a normalized repository path.
#[must_use]
pub fn normalized_parent(path: &str) -> Option<String> {
    if path == "." {
        return None;
    }
    let parent = Path::new(path).parent()?;
    if parent.as_os_str().is_empty() {
        Some(".".to_string())
    } else {
        Some(parent.to_string_lossy().replace('\\', "/"))
    }
}

/// Return a normalized extension for indexing.
#[must_use]
pub fn normalized_extension(path: &Path) -> Option<String> {
    let file_name = path.file_name()?.to_string_lossy();
    if file_name.ends_with(".d.ts") {
        return Some(".d.ts".to_string());
    }
    path.extension()
        .map(|extension| format!(".{}", extension.to_string_lossy().to_lowercase()))
}

#[cfg(test)]
mod tests {
    use super::{normalize_native_path_display_str, repo_path_to_native, validated_repo_file_key};
    use std::io;
    use std::path::Path;

    #[test]
    fn validated_repo_file_key_normalizes_safe_relative_paths()
    -> Result<(), Box<dyn std::error::Error>> {
        require_eq(
            &validated_repo_file_key(Path::new("src\\main.rs"))?,
            "src/main.rs",
        )?;
        require_eq(
            &validated_repo_file_key(Path::new("./src/lib.rs"))?,
            "src/lib.rs",
        )?;
        Ok(())
    }

    #[test]
    fn validated_repo_file_key_rejects_absolute_and_parent_paths() {
        assert!(validated_repo_file_key(Path::new("../secret.rs")).is_err());
        assert!(validated_repo_file_key(Path::new("C:/secret.rs")).is_err());
        assert!(validated_repo_file_key(Path::new("/secret.rs")).is_err());
    }

    #[test]
    fn repo_path_to_native_builds_platform_path_components() {
        assert_eq!(
            repo_path_to_native("src/main.rs"),
            Path::new("src").join("main.rs")
        );
    }

    #[test]
    fn native_path_display_removes_windows_extended_prefixes() {
        assert_eq!(
            normalize_native_path_display_str(r"\\?\C:\repo\.projectatlas\projectatlas.db"),
            "C:/repo/.projectatlas/projectatlas.db"
        );
        assert_eq!(
            normalize_native_path_display_str(r"\\?\UNC\server\share\repo"),
            "//server/share/repo"
        );
        assert_eq!(
            normalize_native_path_display_str("/home/user/repo"),
            "/home/user/repo"
        );
        assert_eq!(
            normalize_native_path_display_str("src\\main.rs"),
            "src/main.rs"
        );
    }

    fn require_eq(left: &str, right: &str) -> Result<(), Box<dyn std::error::Error>> {
        if left == right {
            Ok(())
        } else {
            Err(io::Error::other(format!("expected {right:?}, found {left:?}")).into())
        }
    }
}
